baseURL: https://eens.netlify.app/
title: "Extra Ecclesia Nulla Salus" 

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    weight: 1
    contentDir: content/en
    menu:
      main:
        - name: "ðŸ‡¬ðŸ‡§"
        - identifier: home
          name: Home
          url: /en
          weight: 10
        - identifier: blog
          name: Blog
          url: /en/blog
          weight: 20
        - name: Contact
          url: /en/contact
        - name: FranÃ§ais
          url: /fr
    params:
      dateFormat: "Jan 2, 2006"

  fr:
    languageName: "FranÃ§ais"
    weight: 2
    contentDir: content/fr
    menu:
      main:
        - identifier: home
          name: Accueil
          url: /fr
          weight: 10
        - identifier: blog
          name: Blog
          url: /fr/blog
          weight: 20
        - name: Contact
          url: /fr/contact
        - name: English
          url: /en
    params:
      dateFormat: "2 Jan 2006"
